// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBus8atOZR_Klz9pBZ_Bc_surd3EdgcNWc',
    appId: '1:425569509684:web:5b4b2fc9eedc8b890f8561',
    messagingSenderId: '425569509684',
    projectId: 'car-security-app',
    authDomain: 'car-security-app.firebaseapp.com',
    storageBucket: 'car-security-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBayCFHxNP4qG8vHZE-iwIh53aaUDkZvjQ',
    appId: '1:425569509684:android:3f209cd5b4b8c7550f8561',
    messagingSenderId: '425569509684',
    projectId: 'car-security-app',
    storageBucket: 'car-security-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKgxtAF9bn_sb6l1Nzv5UsSsHOlSm7Tl8',
    appId: '1:425569509684:ios:cd3b7688112b2f590f8561',
    messagingSenderId: '425569509684',
    projectId: 'car-security-app',
    storageBucket: 'car-security-app.appspot.com',
    iosBundleId: 'com.example.lawnShot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKgxtAF9bn_sb6l1Nzv5UsSsHOlSm7Tl8',
    appId: '1:425569509684:ios:cd3b7688112b2f590f8561',
    messagingSenderId: '425569509684',
    projectId: 'car-security-app',
    storageBucket: 'car-security-app.appspot.com',
    iosBundleId: 'com.example.lawnShot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBus8atOZR_Klz9pBZ_Bc_surd3EdgcNWc',
    appId: '1:425569509684:web:89d25edfb475c06c0f8561',
    messagingSenderId: '425569509684',
    projectId: 'car-security-app',
    authDomain: 'car-security-app.firebaseapp.com',
    storageBucket: 'car-security-app.appspot.com',
  );
}
